<?php

$controllers = array(
    'master_app' => 'Master',
    'lang_app' => 'Lang',
    'search_app' => 'Search',
    'captcha_app' => 'Captcha',
    'menu_show_app' => 'MenuShow',
    'menu_list_app' => 'MenuList',
    'article_app' => 'Article',
    'file_upload_app' => 'FileUpload',
    'file_manager_app' => 'FileManager',
    'admin_account_app' => 'Admin.Account',
    'admin_account_create_app' => 'Admin.AccountCreate',
    'admin_account_delete_app' => 'Admin.AccountDelete',
    'admin_account_permission_app' => 'Admin.AccountPermission',
    'admin_account_permission_save_app' => 'Admin.AccountPermissionSave',
    'admin_account_reset_app' => 'Admin.AccountReset',
    'admin_category_app' => 'Admin.Category',
    'admin_category_save_app' => 'Admin.CategorySave',
    'admin_category_delete_app' => 'Admin.CategoryDelete',
    'admin_content_app' => 'Admin.Content',
    'admin_content_view_app' => 'Admin.ContentView',
    'admin_content_save_app' => 'Admin.ContentSave',
    'admin_content_create_app' => 'Admin.ContentCreate',
    'admin_content_delete_app' => 'Admin.ContentDelete',
    'admin_content_edit_app' => 'Admin.ContentEdit',
    'admin_content_hide_create_app' => 'Admin.ContentHideCreate',
    'admin_content_hide_delete_app' => 'Admin.ContentHideDelete',
    'admin_content_search_app' => 'Admin.ContentSearch',
    'admin_content_top_create_app' => 'Admin.ContentTopCreate',
    'admin_content_top_delete_app' => 'Admin.ContentTopDelete',
    'admin_content_single_app' => 'Admin.ContentSingle',
    'admin_content_single_create_app' => 'Admin.ContentSingleCreate',
    'admin_data_app' => 'Admin.Data',
    'admin_data_backup_app' => 'Admin.DataBackup',
    'admin_data_delete_app' => 'Admin.DataDelete',
    'admin_data_recover_app' => 'Admin.DataRecover',
    'admin_index_app' => 'Admin.Index',
    'admin_menu_app' => 'Admin.Menu',
    'admin_menu_view_app' => 'Admin.MenuView',
    'admin_menu_edit_app' => 'Admin.MenuEdit',
    'admin_menu_create_app' => 'Admin.MenuCreate',
    'admin_menu_delete_app' => 'Admin.MenuDelete',
    'admin_menu_save_app' => 'Admin.MenuSave',
    'admin_profile_app' => 'Admin.Profile',
    'admin_profile_edit_app' => 'Admin.ProfileEdit',
    'admin_profile_password_app' => 'Admin.ProfilePassword',
    'admin_setting_app' => 'Admin.Setting',
    'admin_setting_save_app' => 'Admin.SettingSave',
    'admin_sign_in_app' => 'Admin.SignIn',
    'admin_sign_out_app' => 'Admin.SignOut',
);

return get_defined_vars();
